### ISSUE TITLE
Missing U+19D2 (᧒)

### ISSUE THREAD

**Issue by Buernia** [notofonts/new-tai-lue#2]
### Font 
NotoSansNewTaiLue[wght].ttf

### Where the font came from, and when
Site: https://notofonts.github.io/new-tai-lue/fonts/NotoSansNewTaiLue/unhinted/variable-ttf/NotoSansNewTaiLue[wght].ttf
Date: 2022-07-30

### Font Version
2.002

### Issue
 Missing U+19D2 NEW TAI LUE DIGIT TWO (᧒)

### Screenshot
![图片](https://user-images.githubusercontent.com/11886946/181880188-96d18b00-193f-42bc-b66b-a696d1494795.png)

**Comment by simoncozens** [comment]
This was mis-encoded as 0032 DIGIT TWO!

**Comment by Buernia** [comment]
The issue is not fixed in the latest release.
![图片](https://user-images.githubusercontent.com/11886946/189881264-f958cc49-c5f7-495d-a9f1-dbd587b83bf9.png)

**Comment by moyogo** [comment]
Fixed in  #3.
